// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA36-npCa2tAZm8_M9ieXxsOKspF8z2ZP4',
    appId: '1:99608289905:web:18dc9cdb6182b5851df1d0',
    messagingSenderId: '99608289905',
    projectId: 'movies-app-2bb7e',
    authDomain: 'movies-app-2bb7e.firebaseapp.com',
    storageBucket: 'movies-app-2bb7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeLWGTJzLx7wVdxKuGjd8v-cWR0OQGWro',
    appId: '1:99608289905:android:87184ebf78c45ccb1df1d0',
    messagingSenderId: '99608289905',
    projectId: 'movies-app-2bb7e',
    storageBucket: 'movies-app-2bb7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRgFW9Gyu6X84isMm1CgrSn14gmVIpGPU',
    appId: '1:99608289905:ios:33359e95a75c17851df1d0',
    messagingSenderId: '99608289905',
    projectId: 'movies-app-2bb7e',
    storageBucket: 'movies-app-2bb7e.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRgFW9Gyu6X84isMm1CgrSn14gmVIpGPU',
    appId: '1:99608289905:ios:488bcae4188c4afe1df1d0',
    messagingSenderId: '99608289905',
    projectId: 'movies-app-2bb7e',
    storageBucket: 'movies-app-2bb7e.appspot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
